---
- name: Setup Development Environment
  hosts: localhost
  become: true

  vars:
    user_home: "/home/{{ ansible_user }}"

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - zsh
        - curl
        - git
        - nodejs
        - npm
        - python3
        - python3-pip
        - npm
        - openssh-client
        - nala
        - btop
        - timeshift
        - libfuse2
      tags: [packages]

    - name: Install 1Password
      become: true
      snap:
        name: 1password
        classic: true
      tags: [1password]

    - name: Set Git global user name for Todd Costella
      git_config:
        name: user.name
        value: Todd Costella
        scope: global

    - name: Set Git global user email for Todd Costella
      git_config:
        name: user.email
        value: ToddCostella@gmail.com
        scope: global

