---
- name: Setup Development Environment
  hosts: localhost
  become: true

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - zsh
        - git
        - nodejs
        - npm
        - python3
        - python3-pip
        - btop
        - htop
      tags: [packages]

    - name: Install Oh My Zsh
      command: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
      tags: [ohmyzsh]



